
////////////////////////////////////////////////////////////////////////////////
// Auto-generated register configuration file
// Generated by Python register config generator
////////////////////////////////////////////////////////////////////////////////

#include <stdint.h>
#include "init_config.h"

void init_config(void) {

    // RL Scheduler CONFIG REGFILE
    uint64_t *rl_base_addr = (uint64_t *)0x60000000;
    *(rl_base_addr + 0) = 0x0100040008001000;  // RL config regfile 0
    *(rl_base_addr + 1) = 0x103050080f000200;  // RL config regfile 1
    *(rl_base_addr + 2) = 0x1810000a000500cc;  // RL config regfile 2


    // Sensor Collection Unit Configuration
    uint64_t *weight_buffer = (uint64_t *)0x60003000;
    uint64_t *freq_buffer = (uint64_t *)0x60004000;

    // Initialize sensor weight buffers
    // Current (I) weights
    *(weight_buffer + 0) = 0x392456deULL;  // I weight 0
    *(weight_buffer + 1) = 0x00010001ULL;  // I weight 1
    *(weight_buffer + 2) = 0xfffe0001ULL;  // I weight 2
    *(weight_buffer + 3) = 0x01010101ULL;  // I weight 3
    *(weight_buffer + 4) = 0x00000010ULL;  // I weight 4
    *(weight_buffer + 5) = 0xbc8960a9ULL;  // I weight 5
    *(weight_buffer + 6) = 0x00010001ULL;  // I weight 6
    *(weight_buffer + 7) = 0xfffe0001ULL;  // I weight 7
    *(weight_buffer + 8) = 0x01010101ULL;  // I weight 8
    *(weight_buffer + 9) = 0x00000200ULL;  // I weight 9
    // Voltage (V) weights
    *(weight_buffer + 10) = 0xaaaaaaaaULL;  // V weight 0
    *(weight_buffer + 11) = 0x00000080ULL;  // V weight 1
    *(weight_buffer + 12) = 0x46685257ULL;  // V weight 2
    *(weight_buffer + 13) = 0x00000001ULL;  // V weight 3
    *(weight_buffer + 14) = 0xffffffffULL;  // V weight 4
    *(weight_buffer + 15) = 0xaaaaaaaaULL;  // V weight 5
    // Temperature (T) weights
    *(weight_buffer + 16) = 0x00000001ULL;  // T weight 0
    *(weight_buffer + 17) = 0xffffffffULL;  // T weight 1
    *(weight_buffer + 18) = 0x55555555ULL;  // T weight 2
    *(weight_buffer + 19) = 0x80000000ULL;  // T weight 3
    *(weight_buffer + 20) = 0xa3b1799dULL;  // T weight 4
    *(weight_buffer + 21) = 0x00000001ULL;  // T weight 5

    // Initialize sensor frequency buffers
    *(freq_buffer + 0) = 0x0000000000000000ULL;  // Frequencies for sensor 0
    *(freq_buffer + 1) = 0x00000000ffffffffULL;  // Frequencies for sensor 1
    *(freq_buffer + 2) = 0x00000000555556aaULL;  // Frequencies for sensor 2
    *(freq_buffer + 3) = 0x0000000008002008ULL;  // Frequencies for sensor 3
    *(freq_buffer + 4) = 0x00000000960c8190ULL;  // Frequencies for sensor 4
    *(freq_buffer + 5) = 0x00000000105b00b2ULL;  // Frequencies for sensor 5
    *(freq_buffer + 6) = 0x0000000000000000ULL;  // Frequencies for sensor 6
    *(freq_buffer + 7) = 0x00000000ffffffffULL;  // Frequencies for sensor 7
    *(freq_buffer + 8) = 0x00000000555556aaULL;  // Frequencies for sensor 8
    *(freq_buffer + 9) = 0x0000000000480200ULL;  // Frequencies for sensor 9
    *(freq_buffer + 10) = 0x00000000771f43e8ULL;  // Frequencies for sensor 10
    *(freq_buffer + 11) = 0x000000006fe5fc3dULL;  // Frequencies for sensor 11
    *(freq_buffer + 12) = 0x0000000000000000ULL;  // Frequencies for sensor 12
    *(freq_buffer + 13) = 0x00000000ffffffffULL;  // Frequencies for sensor 13

    return;
}
