
////////////////////////////////////////////////////////////////////////////////
// Auto-generated register configuration file
// Generated by Python register config generator
////////////////////////////////////////////////////////////////////////////////

#include <stdint.h>

int main(void) {

    // THERM_TOP CONFIG REGFILE
    uint64_t *therm_top_base_addr = (uint64_t *)0x60002218;
    *(therm_top_base_addr + 0) = 0x000000c80005108a;
    *(therm_top_base_addr + 1) = 0x0000200002002800;
    *(therm_top_base_addr + 2) = 0x001e140a00001410;
    *(therm_top_base_addr + 3) = 0x0000000000053977;

    return 0;
}
